# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bx32qqMePEmgMi66k7dVIGBP1BKIWXsI
"""

x = 5
print (f"變數x的值為:{x}")
print (f"變數x的記憶體地址為:{id(x)}")
